apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: falco-event-generator
  namespace: flux-system
spec:
  targetNamespace: falco
  dependsOn:
  - name: falco
  force: false
  interval: 0m20s
  path: ./fluxcd/infrastructure/falco-event-generator
  prune: true
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: Deployment
    name: falco-event-generator-deployment
    namespace: falco
  sourceRef:
    kind: GitRepository
    name: flux-system
