apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: falco-event-generator
  namespace: falco
spec:
  dependsOn:
  - name: falco
  force: false
  interval: 1m0s
  path: ./fluxcd/infrastructure/falco-event-generator
  prune: true
  healthChecks:
  - apiVersion: apps/v1
    kind: DaemonSet
    name: falco
    namespace: falco
  sourceRef:
    kind: GitRepository
    name: flux-system
