apiVersion: v1
kind: ConfigMap
metadata:
  name: script
data:
  entrypoint.sh: |-
    #!/bin/bash

    timeout 10s \
      /bin/event-generator bench \
        "ReadSensitiveFileUntrusted|WriteBelowBinaryDir" \
        --grpc-unix-socket unix:///var/run/falco/falco.sock  \
        --loop \
        --pid $(pidof -s falco)