apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
spec:
  values:
    # falco:
    #   jsonOutput: true
    #   jsonIncludeOutputProperty: true
    #   httpOutput:
    #     enabled: true
    #     url: "http://falco-falcosidekick:2801"
    falcosidekick:
      enabled: true
      webui:
        enabled: true
    ebpf:
      enabled: true
    leastPrivileged:
      enabled: true
